# Site settings
title: Jordan Ellis-Lynch
description: Jordan Ellis-Lynch is a self-taught Ruby on Rails developer in Melbourne, Australia. Get in contact!
baseurl: ""
url: "https://jordy-el.github.io"

# User settings
username: Jordan Ellis-Lynch
user_description: Self-taught web developer specialising in Ruby on Rails and Javascript
user_title: Ruby on Rails Developer
email: jordan.ellis.lynch@gmail.com
twitter_username: _jordy_el
github_username:  jordy-el

# Google-analytics
google-analytics:
  id: "UA-105445610-1"

exclude: ['package.json', 'src' , 'node_modules']
